name: clash_config_grabber
description: A sample command-line application.
version: 1.0.0
publish_to: "none"
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  xml_parser: ^1.0.0
  hemend_toolkit:
    path: ../hemend_toolkit

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
